Fixes for configuration.

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -4,10 +4,24 @@ dbpath=$(snapctl get dbpath)
 logpath=$(snapctl get logpath)
 args=$(snapctl get args)
 
+dbpath=${dbpath:-"${SNAP_COMMON}/db"}
+logpath=${logpath:-"${SNAP_COMMON}/logs/mongo.log"}
+args=${args:-""}
+
+if [ ! -d "${dbpath}" ]; then
+   echo "error: directory dbpath ${dbpath} does not exist."
+   exit 1
+fi
+
+if [ ! -f "${logpath}" ]; then
+   echo "error: file logpath ${logpath} does not exist."
+   exit 1
+fi
+
 # Should we actually split out db and logs? I don't think thats needed anymore.
 args_file=${SNAP_COMMON}/mongoargs
-echo "--dbpath=${dbpath:-"${SNAP_COMMON}/db"}" > ${args_file}
-echo "--logpath=${logpath:-"${SNAP_COMMON}/logs/mongo.log"}" >> ${args_file}
-echo "${args:-""}" >> ${args_file}
+echo "--dbpath=${dbpath}" > ${args_file}
+echo "--logpath=${logpath}" >> ${args_file}
+echo "${args}" >> ${args_file}
 
 exit 0
